//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUYEN
    {
        public string MAHUYEN { get; set; }
        public string TENHUYEN { get; set; }
        public string MATINH { get; set; }
    }
}
