//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS
{
    using System;
    using System.Collections.Generic;
    
    public partial class THISINH
    {
        public string MAHS { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string SBD { get; set; }
        public string SDT { get; set; }
        public string MAHUYEN { get; set; }
        public string MATINH { get; set; }
        public string MATRUONG { get; set; }
        public string MANGANH { get; set; }
        public string MAKVUT { get; set; }
        public string MADTUT { get; set; }
    }
}
